name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make -C complex_calculator/
      run: make -C complex_calculator/
    - name: make clean
      run: make clean -C complex_calculator/
